name: allcoderelay
description: "Universal code scanner with webhook integration"
publish_to: "none"
version: 1.0.0+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.8
  mobile_scanner: ^3.5.6 # For 2D/3D code scanning
  http: ^1.2.0 # For webhook communication
  shared_preferences: ^2.2.2 # For storing settings
  flutter_bloc: ^8.1.3 # For state management
  go_router: ^13.1.0 # For navigation
  flutter_secure_storage: ^9.0.0 # For secure storage of webhook URL
  package_info_plus: ^5.0.1
  share_plus: ^7.2.1
  sqflite: ^2.3.2
  path: ^1.8.3
  url_launcher: ^6.2.4
  app_links: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
